### ISSUE TITLE
Import in tl_faq

### ISSUE THREAD

**Issue by swinde** [markocupic/import-from-csv-bundle#1]
Ein Import scheint zwar erfolgreich, es werden aber keine Daten geschrieben. 
[tl_faq.zip](https://github.com/markocupic/import-from-csv-bundle/files/1616873/tl_faq.zip)

**Comment by markocupic** [comment]
Hallo Swinde
Hier siehst du ein Beispiel,das funktioniert. Unbedingt eine pid angeben. Die zeigt an, welcher Kategorie der faq zugeordnet wird. Der Autor ist auch eine user id.

Unbedingt mit der neusten Version >= 4.4.8 arbeiten. 

```
id;pid;Sortierindex;question;alias;author;answer;published
2;3;128;"Das ist die Frage";das-ist-die-frage;5;"<p>Hier kommt die Antwort. Zeilenumbrüche in einer CSV sind immer heikel.</p><p>Zeilenumbrüche in einer CSV sind immer heikel.</p>";1
```

**Comment by swinde** [comment]
Hallo Marco,
vielen Dank für die Hilfe! An die Faq Katagorie hatte ich gar nicht gedacht!
ID und Sortierindex muss man nicht angeben, geht auch so.

**Comment by markocupic** [comment]
Ich habe gesehen, dass das Plugin fehlerhaft arbeitet, wenn die csv mit BOM auf der Server geladen wird.
Das sollte in version 4.4.9 nun behoben sein. 
Vielleicht lag es auch daran.
