### ISSUE TITLE
Import in eine Tabelle von MetaModels 2.2

### ISSUE THREAD

**Issue by Werbeagentur-Kopfnuss** [markocupic/import-from-csv-bundle#11]
Hey,

ich will eine csv Datei in eine Tabelle von MetaModels 2.2 improtieren.
Wenn ich die Tabelle auswähle "mm_positions" werden mir nur die Standardspalten/Felder angezeigt - id, pid, sorting, tstamp. Die Attribute/Spalten, die ich angelegt habe kann ich nicht auswählen.

Viele Grüße
Marco

**Comment by markocupic** [comment]
Sollte ab Version 5 nun klappen. Es werden nun alle felder berücksichtigt, auch diejenigen, welche nicht in der DCA hinterlegt sind.
