### ISSUE TITLE
Cronjob Daily

### ISSUE THREAD

**Issue by rallo88** [markocupic/import-from-csv-bundle#12]
Please, please could you add a "daily" Cronjob to the Cronjob-Configuration? Between hourly and weekly?
With best regards
Rallo

**Comment by markocupic** [comment]
Hi Rallo
You are friendly invited to add a pull request to the import-from-csv-bundle.
Regards 
Marko

**Comment by markocupic** [comment]
Fixed in https://github.com/markocupic/import-from-csv-bundle/commit/7d7a4e55819f205a596134ea092e13e1fb7101a3
