### ISSUE TITLE
Import in eigene Tabellen?

### ISSUE THREAD

**Issue by gintabln** [markocupic/import-from-csv-bundle#13]
Guten Tag,
vielen Dank für import-from-csv-bundle! Ich habe leider seit der Update auf Contao 4.9 ein Problem, die Daten in die eigene Tabelle zu importieren. Die Tabelle wird zwar zur Auswahl angezeigt, die Felder können aber nicht mehr abgerufen werden. Habe mehrfach versucht, eigene Tabele zu erstellen und diese dann über import-from-csv-bundle zu befüllen. Immer erscheint die Meldung : Felder für Importvorgang auswählen.* Keine Einträge gefunden.
Haben Sie einen Tip, wie ich rankomme?
Danke im Voraus
Gin

**Comment by markocupic** [comment]
Ist für die Tabelle und deren Felder die DCA vorhanden?
 

--------------------------------------
Marko Cupic
Surenweidstr. 2
CH-6208 Oberkirch

http://4ae-racing-team.ch
http://kletterkader.com

 
 

Gesendet: Freitag, 01. April 2022 um 14:09 Uhr
Von: "gintabln" ***@***.***>
An: "markocupic/import-from-csv-bundle" ***@***.***>
Cc: "Subscribed" ***@***.***>
Betreff: [markocupic/import-from-csv-bundle] Import in eigene Tabellen? (Issue #13)


 

Guten Tag,
vielen Dank für import-from-csv-bundle! Ich habe leider seit der Update auf Contao 4.9 ein Problem, die Daten in die eigene Tabelle zu importieren. Die Tabelle wird zwar zur Auswahl angezeigt, die Felder können aber nicht mehr abgerufen werden. Habe mehrfach versucht, eigene Tabele zu erstellen und diese dann über import-from-csv-bundle zu befüllen. Immer erscheint die Meldung : Felder für Importvorgang auswählen.* Keine Einträge gefunden.
Haben Sie einen Tip, wie ich rankomme?
Danke im Voraus
Gin

**Comment by gintabln** [comment]
Danke für die Antwort. Ich habe die neueste Version installiert. Jetzt geht alles wieder!
