### ISSUE TITLE
Importfehler

### ISSUE THREAD

**Issue by jankout** [markocupic/import-from-csv-bundle#15]
Hallo, ich bekomme folgende Fehlermeldung, wenn ich den Import starte. Dabei benutze ich PHP 8.1, Contao 4.13.19 und ich möchte die Daten in _**tl_news**_ importieren. Der Importtest verläuft eigentlich gut - da ist allgemein eine Diskrepanz zwischen dem Test und realen Import, weil der Testimport weniger fehlerhaft ausfällt.

`Uncaught PHP Exception Twig\Error\RuntimeError: "Key "showAllBtn" for array with keys "new, renderAppAction, title_legend, docs_legend, settings_legend, limitAndOffset_legend, cron_legend, title, importTable, importMode, fieldEnclosure, fieldSeparator, selectedFields, fileSRC, fileContent, skipValidationFields, offset, limit, enableCron, cronLevel, truncate_table, append_entries, runImportBtn, testRunImportBtn, showErrorsBtn, showAllButton, btnImport, btnImportTest, editItemTitle, data_records, successful_inserts, failed_inserts, info_text, data_record_insert_failed, data_record_insert_succeed, confirm_start_import, exception_message, import_process_completed, import_process_started, loading_application, id, tstamp, explanation, listLines" does not exist." at /www/htdocs/w017add7/marxelinho.net/contao/vendor/markocupic/import-from-csv-bundle/templates/import.html.twig line 39`

**Comment by markocupic** [comment]
PHP- und Contao Version?

**Comment by jankout** [comment]
Siehe oben.

**Comment by markocupic** [comment]
Habe soeben mit einem Mitgliederimport die Anwendung getestet. Läuft alles sauber durch. Kannst du mal im Contao Manager oder perConsole `composer update` machen.

**Comment by jankout** [comment]
Hallo, danke für die schnelle Erledigung. Ich kann es nur im CM machen. Soll ich nur dein Paket aktualisieren?

**Comment by markocupic** [comment]
Ja, nur mein Paket als erstes.--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 18.04.23, 14:19 schrieb Jan Kout ***@***.***>:

   
  Hallo, danke für die schnelle Erledigung. Ich kann es nur im CM machen. Soll ich nur deine Paket aktualisieren?

**Comment by jankout** [comment]
ich habe die Aktualisierung durchgeführt, allerdings bekomme ich weiterhin die Fehlermeldung. Hier mein CSV nur mit einem Eintrag als Test. Dabei habe ich folgendes im Backend eingestellt. 

<img width="1220" alt="screenshot 2023-04-18 v 14 25 23" src="https://user-images.githubusercontent.com/3715050/232776626-93da3128-b84c-4127-81a1-f42fbe05bb50.png">



[blog_entry DJango Import Contao - 2.csv](https://github.com/markocupic/import-from-csv-bundle/files/11261680/blog_entry.DJango.Import.Contao.-.2.csv)

**Comment by markocupic** [comment]
Auf den ersten Blick sehe ich, dass ein pid Feld fehlt. Ohne pid (parent id) wird dein News-Beitrag keinem Newsarchiv zugeordnet. 

Damit das Feld 'tstmp' korrekt importiert wird, musst du nochmals updaten auf Version 5.2.5. Danach hat bei mir der Import mit deinem Testdatensatz tadellos funktioniert. 

Welche andere Extensions hast du installiert? Wie sieht dein composer.json Datei aus?

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/1525166/232802771-3a5adda5-5e86-4630-818b-377984f88200.png">

**Comment by jankout** [comment]
Super. Danke. Ich probiere es nun mit mehr Sachen. 

Eine allgemeine Frage: soll ich die ID nie importieren, weil es bei der Datenbank automatisch steigt?

**Comment by markocupic** [comment]
Id nie, aber pid schon. 

Aber ich denke, wir wissen immer noch nicht, weshalb es bei dir zu diesem Fehler kommt. 

Du hast schon die Version 5.2.5 im Betrieb oder?

**Comment by jankout** [comment]
Genau, diese benutze ich bereits und es hat mit dem Import überwiegend geklappt. Nur bei ca. 30 Einträgen von 648 nicht. Es wäre super einen Log zu haben, wo ich es anschaue könnte. 

Falls es für dich schneller geht, können wir uns das auch direkt über Bildschirmfreigabe anschauen.

**Comment by markocupic** [comment]
Und es kommt immer noch diese Fehlermeldung?
> `Uncaught PHP Exception Twig\Error\RuntimeError: "Key "showAllBtn" for array with keys "new, renderAppAction, title_legend, docs_legend, settings_legend, limitAndOffset_legend, cron_legend, title, importTable, importMode, fieldEnclosure, fieldSeparator, selectedFields, fileSRC, fileContent, skipValidationFields, offset, limit, enableCron, cronLevel, truncate_table, append_entries, runImportBtn, testRunImportBtn, showErrorsBtn, showAllButton, btnImport, btnImportTest, editItemTitle, data_records, successful_inserts, failed_inserts, info_text, data_record_insert_failed, data_record_insert_succeed, confirm_start_import, exception_message, import_process_completed, import_process_started, loading_application, id, tstamp, explanation, listLines" does not exist." at /www/htdocs/w017add7/marxelinho.net/contao/vendor/markocupic/import-from-csv-bundle/templates/import.html.twig line 39`

**Comment by jankout** [comment]
Auf jeden Fall hat es mit dem Import geklappt. Ob der Fehler immer noch kommt, weiß ich nicht, weil ich es nicht mehr im Debugmode durchführte. Soll ich es noch probieren?

**Comment by markocupic** [comment]
Ja, aktualisere doch noch einmal auf die neuste Version meiner Extension und führe den Import noch einmal im Debug-Mode durch. Ich habe das Log noch etwas verbessert, so dass du mehr Informationen bei Fehlern angezeigt bekommst.

**Comment by jankout** [comment]
Alles funktioniert einwandfrei. Vielen Dank für deine schnelle und richtige Hilfe. Das schätze ich sehr.
