### ISSUE TITLE
Import von Newsletter-Abonnements in tl_member

### ISSUE THREAD

**Issue by FrischBlau** [markocupic/import-from-csv-bundle#16]
Hi Marko,

beim Import von Mitgliedern in die tl_members werden die Newsletter-Abonnements nicht mit übernommen. Hab dunkel im Kopf, dass es das vor ein paar Jahren schon mal gab(?). Möglicherweise aber auch ein Fehler bei mir: In der csv muss die ID des Newsletters stehen, richtig?
Contao 4.13, import-from-csv-bundle 5.3.2, PHP 8.1

**Comment by markocupic** [comment]
Ich würde sagen:

```
username;newsletter
dirtyharry;1
clinteastwood;1||2||3
```
Mehrere Newsletter Abos trennst du mit dem Pipe Zeichen.

**Comment by FrischBlau** [comment]
Genau das war der Plan. Beim Import werden die Member brav in die tl_member eingefügt mit sämtlichen Daten. Nur die Newsletter Abos werden als Einziges nicht übernommen.

**Comment by markocupic** [comment]
Der Fehler ist nicht reproduzierbar. Soeben getestet.
<img width="380" alt="image" src="https://github.com/markocupic/import-from-csv-bundle/assets/1525166/8529f405-7834-4d2b-acde-fae553573f2c">

<img width="1094" alt="image" src="https://github.com/markocupic/import-from-csv-bundle/assets/1525166/8ada047c-9ba3-44cd-9c67-50ad75ab555e">

<img width="565" alt="image" src="https://github.com/markocupic/import-from-csv-bundle/assets/1525166/b2d5b332-8089-4ccb-9084-f032bfdd1465">

**Comment by markocupic** [comment]
Hast du das Feld "newsletter" in den Import Settings angewählt?

<img width="361" alt="image" src="https://github.com/markocupic/import-from-csv-bundle/assets/1525166/7ffbec14-a9f3-4259-882e-7119984e2711">

**Comment by FrischBlau** [comment]
Danke und ja, das Feld "newsletter" in den Import Settings habe ich angewählt :-) Beim Import wird mir auch angezeigt, dass "newsletter" berücksichtigt wurde. Inzwischen habe ich mit der gleichen csv und den gleichen Einstellungen in zwei anderen Installationen getestet, dort läuft alles problemlos. Muss also an der speziellen Installation liegen.

**Comment by marcelhoenerbach** [comment]
Ich habe zu diesem Thema noch etwas herausgefunden. Bei mir scheint es so zu sein, dass der Import der Newsletter-Empfänger nur dann funktioniert, wenn der Import-Modus auf "Tabelle vor dem Import leeren" steht. Mit "Datensätze anhängen" scheint es Probleme zu geben.

**Comment by markocupic** [comment]
The issue should be fixed now. See 88d4a050ca51a4520e9340f4c0018899dd2fcdfc
