### ISSUE TITLE
Import member newsletter subscription

### ISSUE THREAD

**Issue by marcelhoenerbach** [markocupic/import-from-csv-bundle#17]
It is not possible to import the newsletter subscription by ID in tl_member > newsletter.

**Comment by markocupic** [comment]
Why not?

**Comment by marcelhoenerbach** [comment]
The following is an example of the import file:

company;firstname;lastname;email;newsletter
[company];[firstname];[lastname];info@kundendomain.tld;6

6 is the ID of the newsletter in Contao. This works fine with the groups for example, but not with the newsletter subscription. When I check the member in the backend, the corresponding newsletter subscription is not activated.

**Comment by markocupic** [comment]
Does it works, if you change the order of the columns in your CSV? Try to run the import with the newsletter column on the second position.

**Comment by marcelhoenerbach** [comment]
Unfortunately, it's the same as well when I run the import with the newsletter column on the second position.

**Comment by markocupic** [comment]
I can not reproduce your issue. See
https://github.com/markocupic/import-from-csv-bundle/issues/16

Please contact me via Email for a further debugging.
