### ISSUE TITLE
tl_member `groups` wird übersprungen

### ISSUE THREAD

**Issue by ngdot** [markocupic/import-from-csv-bundle#18]
Hi, unter Contao 4.13.34 mit PHP 8.2 wird der Import von Mitgliedern in die Tabelle tl_member das Feld `groups` einfach übersprungen, selbst mit deiner Test CSV.

**Comment by markocupic** [comment]
Hi @ngdot 
I cannot reproduce your issue. Could you post or send me an anonymized version of your CSV file?

**Comment by ngdot** [comment]
I've made a new test, fresh Contao 4.13 with just your extension. Same problem.
I attached some screenshots and the test file (which is yours [just added the "https://" for the websites]).
What surprises me is the display of the "groups" field on the import setup. It seems to be not recognized by the extension. As you can see, the import skips this field entirely. 
Im using symfony webserver on macos with php-fpm 8.2 and mysql 8.0.27

[test.csv](https://github.com/markocupic/import-from-csv-bundle/files/13325618/test.csv)

![SCR-20231111-mwrz](https://github.com/markocupic/import-from-csv-bundle/assets/8327905/87b8f1ef-e598-4cd8-8222-856b0aab8b9e)

![SCR-20231111-mwut](https://github.com/markocupic/import-from-csv-bundle/assets/8327905/a93f3970-ecaa-4b89-8f86-aa8c0868b796)

![SCR-20231111-mwwr](https://github.com/markocupic/import-from-csv-bundle/assets/8327905/07b868ba-3a84-44bd-8e16-6fcb016cf87b)

**Comment by markocupic** [comment]
What happens if you surround the word "groups" with backticks in the header row of your CSV?

**Comment by ngdot** [comment]
If I surround the word "groups" with backticks, the import works partially.
If there is a single value for "groups" in a row like `1`, it works – but if we got two values with the shema `1||2` it doesnt work.

![image](https://github.com/markocupic/import-from-csv-bundle/assets/8327905/3e6695dd-d942-4dcd-b276-50d9d112fb01)

![image](https://github.com/markocupic/import-from-csv-bundle/assets/8327905/74a8c3c5-e22a-472a-a09a-b6b6b556b89f)

**Comment by markocupic** [comment]
@ngdot Please contact me via email to arrange how we could debug this issue.
