### ISSUE TITLE
Import in tl_member

### ISSUE THREAD

**Issue by swinde** [markocupic/import-from-csv-bundle#2]
Beim Import in die tl_member Tabelle bringt der Testmod bei mir Fehler.
Als csv Datei habe ich die example.csv genommen, um zu schauen was geht. Nur in der Spalte "groups"
habe ich die ID's der Mitgliedergruppen geändert.
Beim Datum bin ich mir nicht sicher, ob das nicht durch Open Calc falsch formatiert wurde.
Siehe Screenshot:

![member_testmode](https://user-images.githubusercontent.com/3349884/34746692-3fddb568-f595-11e7-992b-bd8661a9f284.jpg)

[example.zip](https://github.com/markocupic/import-from-csv-bundle/files/1616882/example.zip)

**Comment by markocupic** [comment]
Ja, das Datum muss in der csv in genau dem Format vorliegen, wie du es in den Backend-Einstellungen festgelegt hast. 
Das scheint hier so etwas zu sein: 25.05.1977

Tipp: Unbedingt mit der Version 4.4.8 arbeiten.

**Comment by swinde** [comment]
Das Datum ist mir nicht so wichtig! Die Zuordnung zu den Mitgliedergruppen wäre mir wichtiger!

**Comment by markocupic** [comment]
Zuordnung zu den Mitgliedern musst du z.B. so angeben:
1||2||5

Gehe auf Version: 4.4.9.
Siehe https://github.com/markocupic/import-from-csv-bundle/issues/1

**Comment by swinde** [comment]
Ich habe das jetzt noch mal in einer anderen Contao4 Installation getestet, die membergroups werden nicht eingetragen. Wenn ich das Feld leer lasse dann gibt der Testmodus "a:0:{}" aus.
Aber wie auch immer, das Modul ist super! So schnell habe ich noch nie meine Events eingetragen!

Danke

**Comment by markocupic** [comment]
Wie sieht denn deine csv aus? Kannst du mir mal eine Zeile posten oder senden?
Die Member Gruppen, die du im csv referenzierst existieren die auch tatsächlich und haben die in der csv eingetragene ID?

**Comment by swinde** [comment]
Es gibt 2 Gruppen mit id 1 und 2.
Dementsprechend gebe ich bei groups 1 oder 2 ein. Das akzeptiert das Modul auch nicht.
Die example.zip ist im ersten Post angehangen.

**Comment by markocupic** [comment]
Das ist mir fast schon langsam peinlich...
Willst du nochmals probieren mit Version 4.4.10 ?
Liebe Grüsse
Marko

**Comment by markocupic** [comment]
Wenn dir der Importer gefällt.
Vielleicht wäre dann das hier auch etwas für dich. Ein Exporter.
https://github.com/markocupic/export_table

**Comment by swinde** [comment]
Es gibt 2 Gruppen mit id 1 und 2.
Dementsprechend gebe ich bei groups 1 oder 2 ein. Das akzeptiert das Modul auch nicht.
Die example.zip ist im ersten Post angehangen.

**Comment by swinde** [comment]
Version 4.4.10 funktioniert! Suuuuuper!
Den Exporter schaue ich mir Morgen mal an! Schönen Feierabend!!!
