### ISSUE TITLE
startDate-Feld, falsche Ausgabe, da falscher Unixtimestamp bei den Zeiten

### ISSUE THREAD

**Issue by mj1985** [markocupic/import-from-csv-bundle#20]
Moin,
ich möchte über eine CSV Events einfügen, das klappt auch soweit, allerdings wird im Backend als `startDate` immer das aktuelle Datum gesetzt. Das `startDate` wird korrekt vom `d.m.Y` Format in UnixTimestamp umrechnet und in der DB gespeichert.

Datum im Backend:
![image](https://github.com/user-attachments/assets/af2c932e-b0f2-42ab-be2e-4ae393e81fb6)

Speichere ich den Datensatz in den Events einmal neu ab, wird das Datum korrekt gesetzt.
Nach dem Speichern in Contao wird `startTime` und `endTime` noch in die DB geschrieben, wenn ich diese Werte mitgebe (z. B. 17:00), wird  der Unixtimestamp mit dem aktuellen Datum und der übermittelten Uhrzeit erstellt. So klappt es nicht.
Wenn ich einen Hook einsetze und mir den Unixtimestamp selbst erstelle und speichern will, wird beim Import gemeckert, dass die Uhrzeit nicht konform ist (selbst wenn ich das Feld aus der Validierung raus nehme).
Hat jemand dieses Problem schon gelöst?

Testdaten: [tl_calendar_events_20221112_140643.csv](https://github.com/user-attachments/files/16636921/tl_calendar_events_20221112_140643.csv)

Rahmenbedingungen:
Contao 4.13.46
PHP 8.3.16
markocupic/import-from-csv-bundle 5.3.4

**Comment by markocupic** [comment]
@mj1985 Ich kann deinen Fehler nicht reproduzieren. 
Du kannst https://github.com/markocupic/export_table nutzen um eine CSV der bestehenenden Events zu erhalten. Dann siehst du auch, wie die Datums-Werte formatiert sein sollen.

**Comment by mj1985** [comment]
Ich habe nun https://github.com/markocupic/export_table ausprobiert, also die Daten vorher bearbeitet, so dass sie im Backend korrekt angezeigt werden und habe die Daten neu importiert, gleiches Problem.
Übersichtsseite
![image](https://github.com/user-attachments/assets/9a3843db-ed8c-4aa3-878e-9932cdea9cbc)
Einstellungen (korrektes Datum!)
![image](https://github.com/user-attachments/assets/54bd2727-cbfe-43e0-a921-70722b3f48cd)
Nach dem Speichern
![image](https://github.com/user-attachments/assets/3fc1e088-c9d0-4d6d-a336-c9b775e37b22)

**Comment by markocupic** [comment]
Ah, du hast Recht. Ich habe deinen ersten Post nicht richtig gelesen. 
Das wirst du nur mit einem Event Listener lösen können, der auf den [PostImportEvent](https://github.com/markocupic/import-from-csv-bundle/blob/master/src/Event/PostImportEvent.php) hört. 

Und zwar musst du deiner Uhrzeit beim Feld startTime oder endTime noch einen base-timestamp mitgeben. Fehlt dieser, nimmt die [strtotime()](https://www.php.net/manual/en/function.strtotime.php) Funktion automatisch den heutigen Tag. Das System kann ja nicht erraten, welches Datum du meinst mit 20:30 Uhr.

**Comment by mj1985** [comment]
Hat wunderbar funktioniert mit dem PostImportEvent.
Danke @markocupic ❤️
