### ISSUE TITLE
Contao-URL dynamisch übernehmen

### ISSUE THREAD

**Issue by jankout** [markocupic/import-from-csv-bundle#22]
Wenn man eigene Contao-Url hat, also statt _**contao**_, _**admin**_, übernimmt eure Erweiterung das noch nicht, was man sich eigene URL erstellt hat. Es wäre toll, wenn es dynamisch übernommen werden könnte, damit die gängige Navigation (z.B. zurück) innerhalb eurer Erweiterung funktioniert. Danke.

**Comment by markocupic** [comment]
@jankout Would you please check, if the issue still occurs in the latest [5.x version](https://github.com/markocupic/import-from-csv-bundle/tree/5.3.8)?

**Comment by jankout** [comment]
Sehr gut. Es funktioniert.  :-)  

Eine andere Frage: wenn ich in eine bestehende Tabelle nur eine Spalte importieren und dabei die bestehenden Sachen überschreiben möchte, geht es momentan mit deiner Erweiterung nicht, oder?

**Comment by markocupic** [comment]
> Eine andere Frage: wenn ich in eine bestehende Tabelle nur eine Spalte importieren und dabei die bestehenden Sachen überschreiben möchte, geht es momentan mit deiner Erweiterung nicht, oder?

No, this isn't possible at the moment.
