### ISSUE TITLE
Modul wird im Contao Manager nicht gefunden.

### ISSUE THREAD

**Issue by swinde** [markocupic/import-from-csv-bundle#3]
Hallo ich habe gerade versucht, das Modul über den CM zu installieren! 
> Keine Ergebnisse für markocupic/import-from-csv-bundle

Bei anderen Modulen kommt unter Paketdetails auf packagist.org/ 
502 Bad Gateway
VG Steffen Winde

**Comment by markocupic** [comment]
Kann ich nicht bestätigen. Soeben getestet.
Lg Marko

**Comment by swinde** [comment]
Ja. Geht wieder! Da hat vielleicht der Server packagist.org gesponnen! 
Danke!
Issue kann geschlossen werden!
