### ISSUE TITLE
Import in tl_member läuft in ein Time-Out

### ISSUE THREAD

**Issue by mdriverch** [markocupic/import-from-csv-bundle#5]
Der Import unserer CSV läuft in eine Time-Out. Nach ca. 5 min
Die CSV hat ca. 2950 einträge mit Benutzerdaten.
Wen für das Feld "password [varchar]" die Validierung überspringe, läuft es ohne Probleme durch. Jedoch sind dan die Passwort nicht verschlüsselt in der DB. 
Es läuft PHP 7.2.25 auf dem Server. Habe ich etwas vergessen zu Konfigurieren?

**Comment by mdriverch** [comment]
Unterstützt das Modul Argon2 password hashing?

**Comment by markocupic** [comment]
Man müsste wohl 2 neue Felder einbauen: LIMIT und OFFSET.
Um nicht die max_script_execution zu überschreiten.

**Comment by markocupic** [comment]
> Unterstützt das Modul Argon2 password hashing?

Nein ;-)

**Comment by markocupic** [comment]
The extension supports Argon2 password hashing, offset and limit from version 4.5.0.
