### ISSUE TITLE
Import fails

### ISSUE THREAD

**Issue by wernerjoss** [markocupic/import-from-csv-bundle#7]
I just tried this Plugin in a contao 4.9.12 docker instance and tried to import a csv file.
filled out all necessary Informations, selected fields to import, but then got this:
`
Internal Server Error
Was ist das Problem?

Attempted to call an undefined method named "fetchAssociative" of class "Doctrine\DBAL\Driver\PDOStatement".
`
what could I try next ?

**Comment by markocupic** [comment]
Ok. Schaut aus, als dass die Extension als Mindestvoraussetzung doctrine/dbal in Version >=2.11 verlangt. 
Welche Version ist installiert? 2.10?
Grüsse Marko

**Comment by markocupic** [comment]
Deinstalliere markocupic/import-from-csv-bundle
und installiere die Extension mit folgender Versionsbedingung:
"markocupic/import-from-csv-bundle: "4.7.*"
Das sollte das Problem lösen.
Lg Marko

**Comment by wernerjoss** [comment]
> Ok. Schaut aus, als dass die Extension als Mindestvoraussetzung doctrine/dbal in Version >=2.11 verlangt.
> Welche Version ist installiert? 2.10?

es ist 2.10.4

**Comment by wernerjoss** [comment]
> Deinstalliere markocupic/import-from-csv-bundle
> und installiere die Extension mit folgender Versionsbedingung:
> "markocupic/import-from-csv-bundle: "4.7.*"

ok, hab ich gemacht.

> Das sollte das Problem lösen.

leider nicht: beim test mit einer kleinen csv Datei (~10 Zeilen) bekomme ich den Datei Inhalt im Import Testmodus richtig angezeigt, aber der Import selbst klappt nicht, es nudelt bis zum Timeout (max_execution_time 240 sec, das sollte ja eigentlich reichen).
das ist jetzt aber offenbar ein anderes Problem, ich werde mal noch andere Einstellungen probieren (Trennzeichen, ignore...).
jdenfalls erstmal Danke !
Gruss
Werner

**Comment by markocupic** [comment]
Ok. Ich sehe es. Das ging gestern wohl etwas zu schnell ;-)
Mache nochmals ein Update. Version 4.7.16 sollte nun laufen. ;-)
Sonst wieder melden.
Lg marko

**Comment by wernerjoss** [comment]
wow, schon ein update 😄 
habs gleich probiert, Import im Testmodus funktioniert jetzt mit einer 2-zeilen-csv Datei, ´daten werden richtig angezeigt.
aber wenn ich den echten Import starte, kommt nun ein anderer doctrine Fehler:
`Attempted to call an undefined method named "executeStatement" of class "Doctrine\DBAL\Connection".`
doctrine\dbal ist wie gesagt 2.10.4
Gruss
Werner

**Comment by markocupic** [comment]
Ja, ich habe eben kein dbal in Version 2.10 installiert.
Probier nochmals mit einem Update auf 4.7.17
Lg Marko

**Comment by wernerjoss** [comment]
Moin Marko,
hab die 4.7.17 probiert - funktioniert laut Backend - siehe screenshot.
allerdings ist die Tabelle in die importiert werden soll, leer (vor und nach dem Import).
Lg
Werner
![grafik](https://user-images.githubusercontent.com/36265757/109926641-78145f00-7cc3-11eb-98dd-14e2db2e303e.png)

**Comment by wernerjoss** [comment]
Moin Marko,
super, es funktioniert nun - danke !
Lg
Werner
