### ISSUE TITLE
Import empty(optional) float fields fail.

### ISSUE THREAD

**Issue by danielkochc** [markocupic/import-from-csv-bundle#8]
I tried to import some csv files into different tables. Everything works fine until i have some data sets with empty (optional) float values. If I change the field type to varchar it works, if all float fields of the data set are filled and not empty it works too.

What I tried so far:
Not working:
- `float_field` FLOAT(12) NOT NULL DEFAULT '0'
- `float_field` FLOAT(12) NULL DEFAULT '0'
- `float_field` FLOAT(12) NULL DEFAULT NULL,

Working:
- `float_field` VARCHAR(50) NULL DEFAULT NULL
- `float_field` VARCHAR(50) NOT NULL DEFAULT ''

If I skip the validation of the critical fields it doesn't work ether.
Import test mode works, but import process does not.

**Comment by markocupic** [comment]
Do you use dca arrays to build database tables? The extension sets empty values from dca's sql parameter.

Have you tried?

```
// Float field for positive values only (x >= 0)
$GLOBALS['TL_DCA']['tl_member']['fields']['test'] = [
    'inputType' => 'text',
    'exclude'   => true,
    'eval'      => array('mandatory' => false, 'rgxp' => 'digit', 'maxlength' => 255, 'tl_class' => 'w50'),
    'sql'       => "DOUBLE unsigned NOT NULL default '0'"
];

// Float field if you expect negative values
$GLOBALS['TL_DCA']['tl_member']['fields']['test'] = [
    'inputType' => 'text',
    'exclude'   => true,
    'eval'      => array('mandatory' => false, 'rgxp' => 'digit', 'maxlength' => 255, 'tl_class' => 'w50'),
    'sql'       => "DOUBLE NOT NULL DEFAULT '0'"
];

```

**Comment by danielkochc** [comment]
Thanks for your reply,

No I don't use dca arrays. I created the tables directly and set the default values as mentioned in my first post. I tried to set the data type to double as well. The extract of the create code is:

`float_field_1` DOUBLE(22,0) NOT NULL DEFAULT '0',
`float_field_2` DOUBLE(22,0) NOT NULL DEFAULT '0',

and so on, which matches the sql parameters contao uses. According to my understandig, the default values of the columns should be taken, because the importer didn't know anything about any dca's? 

FYI:
For example the filesize field in the tl_search is defined by a sql parameter from the tl_search dca and is exactly the same in terms of the create code for the table.

`filesize` DOUBLE(22,0) NOT NULL DEFAULT '0',

PS: I use HeidiSQL to extract the create codes and edit my database remotely.

**Comment by markocupic** [comment]
I recommend you to use dca array when using the csv import bundle. Without the information, which is stored in the dca array,  the importer can't validate the user input nor it will be able to set the correct empty value. 

```
$GLOBALS['TL_DCA']['tl_member']['fields']['test'] = [
    'inputType' => 'text',
    'sql'       => "DOUBLE NOT NULL DEFAULT '0'"
];
```
Setting the inputType and the sql-Paramater like showed above, should be enough for a proper import.

**Comment by danielkochc** [comment]
Thanks for your help, I will try that.

I found out, I used the outdated version 4.6.3 which can be used with generic non-dca created tables, which was really nice in my opinion. I will rework my code now.
